FROM node:10.4.1-alpine

WORKDIR /usr/src/app

ENV PATH /usr/src/app/node_modules/.bin:$PATH

COPY package.json /usr/src/app/package.json
RUN npm install --slient
RUN npm config set unsafe-perm true
RUN npm install react-scripts -g --slient

CMD ["npm", "start"]
